Adding mondo
EBI-G2P/ensembl-gene2phenotype pull request #61
Opened 2022-04-06 08:42 UTC by olaaustine

[ENSVAR-4684](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4684)

2022-04-13 16:26 UTC, sarahhunt requested changes
Hi @olaaustine, here are some initial comments on the MONDO support.

2022-04-13 16:26 UTC, sarahhunt commented on modules/Bio/EnsEMBL/G2P/Utils/Downloads.pm
> +  $csv->print($fh, ['gene symbol', 'gene mim', 'disease name', 'disease mim', 'disease ontology', 'confidence category', 'allelic requirement', 'mutation consequence', 'phenotypes', 'organ specificit
It would be safer to add the new term to the end of the file in case anyone parsing it is relying on the order.

2022-04-13 16:26 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +- disease mondo
We just have one column for disease accession here rather than disease mim and disease mondo

2022-04-13 16:26 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +  my $disease_mondo = $data{'disease mondo'};
we would need to check if the disease accession matches MONDO or MIM before assigning here

2022-04-13 16:26 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +          -description        => $given_mondo_descript,
The description we would want to store here is the MONDO term. So if the accession submitted is MONDO:0016587 the description would be arrhythmogenic right ventricular cardiomyopathy. The same goes for the above.

We can leave this null in the first instance to get data in.

2022-04-13 16:26 UTC, sarahhunt commented on sql/patch_104_105_h.sql
> +  ontology_accession VARCHAR(255) DEFAULT NULL,
This is better not null as there is no point to the record without it.

2022-04-13 16:26 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +     my $attribute = "Data source";
If we import the MONDO accession supplied, we can say it comes from the submitter/data source. If we obtain it using OLS we need to say we got it from OLS. get_ontology_accession may do either here. 
We can start by only importing supplied MONDO accessions in the first instance.

2022-04-13 17:28 UTC, olaaustine commented on modules/Bio/EnsEMBL/G2P/Utils/Downloads.pm
> +  $csv->print($fh, ['gene symbol', 'gene mim', 'disease name', 'disease mim', 'disease ontology', 'confidence category', 'allelic requirement', 'mutation consequence', 'phenotypes', 'organ specificit
This has been resolved.

2022-04-20 07:08 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +      my $attribute = "Data source";
These MONDO terms are being assigned by OLS, rather than the data supplier, so 'Data source' is not appropriate

2022-04-20 07:09 UTC, sarahhunt commented on scripts/populate_panels/load_g2p_data.pl
> +      my $mondo_attribute = "OLS exact";
These MONDO terms are supplied by the data provider rather than mapped with OLS

2022-04-21 08:54 UTC, dglemos commented on scripts/populate_panels/load_g2p_data.pl
> +          -description        => "NULL",
The description is being inserted as a string. To set it null it should be:
`-description        => undef,`

2022-04-21 10:28 UTC, dglemos commented on modules/Bio/EnsEMBL/G2P/DiseaseOntology.pm
> +    if ($self->{mapped_by_attrib} && !$self->{mapped_by}){
You can use `elsif ()` instead.

2022-04-21 10:30 UTC, dglemos commented on modules/Bio/EnsEMBL/G2P/DiseaseOntology.pm
> +    if (!defined $self->{mapped_by_attrib} && defined $self->{mapped_by}){
You can use `elsif ()` instead.

2022-04-21 10:36 UTC, dglemos commented on modules/Bio/EnsEMBL/G2P/Utils/Downloads.pm
> +    my $ontology = ($disease_id && $ontology_accession->{$disease_id}) ? $ontology_accession->{$disease_id} : "No ontology";
If there is no ontology then we could leave it empty.

2022-04-21 10:40 UTC, dglemos commented on scripts/populate_panels/load_g2p_data.pl
> +          -description        => $mondos_label->{$mondo_id},
Could add `|| undef`:
`-description        => $mondos_label->{$mondo_id} || undef,`

2022-04-21 13:43 UTC, dglemos commented on modules/Bio/EnsEMBL/G2P/DBSQL/OntologyTermAdaptor.pm
> +    $ontology_accession->description,
Could also be `$ontology_accession->description || undef,`

2022-04-21 15:28 UTC, merged